project_name: image-refresher
release:
  github:
    owner: huseyinbabal
    name: image-refresher
builds:
  - id: image-refresher
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/huseyinbabal/image-refresher/pkg/version.version=
archives:
  - id: image-refresher
    builds:
    - image-refresher
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
