apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: image-refresher
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/huseyinbabal/image-refresher/releases/download/v0.1.0/image-refresher_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./image-refresher"
      to: "."
    - from: LICENSE
      to: "."
    bin: "image-refresher"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/huseyinbabal/image-refresher/releases/download/v0.1.0/image-refresher_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./image-refresher"
      to: "."
    - from: LICENSE
      to: "."
    bin: "image-refresher"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/huseyinbabal/image-refresher/releases/download/v0.1.0/image-refresher_windows_amd64.zip
    sha256: ""
    files:
    - from: "/image-refresher.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "image-refresher.exe"
  shortDescription: A new plugin
  homepage: https://github.com/huseyinbabal/image-refresher
  caveats: |
    Usage:
      $ kubectl image-refresher

    For additional options:
      $ kubectl image-refresher --help
      or https://github.com/huseyinbabal/image-refresher/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
